---
# most of these variables should be passed in to ansible with --extra-vars "@your_file.json"
wiki:
  install_path: /var/www/html/
  user: apache
  site_name: MediaWiki
  meta_namespace: MediaWiki
  base_url: http://www.mediawiki.com
  domain: mediawiki
  secret_key: a1234567890
  upgrade_key: a12345
  cache:
    type: CACHE_NONE
    mem_cached_servers: array()
  db:
    type: mysql
    server: mysql.rds.endpoint
    name: wiki
    user: wiki
    password: dbpassword
    prefix: ""
    table_options: "ENGINE=InnoDB, DEFAULT CHARSET=binary"
